glossary.rst
=> Add links and new terms to glossary

technologies.rst
I have shifted my glossary terms from glossary to technologies.rst. @nemesisdesign Please review
=> technologies updated

technologies.rst
Added Lua and Shell to technologies
=> Technologies

developer/contributing.rst
Contribution Guidelines for our Organization
fixes #7
=> Documentation for contributing guidelines

developer/google_code_in.rst, index.rst
Contains some resources for programming languages and networking
=> Added GCI page

developer/contributing.rst
Contributing guidelines have been updated. The deliverables of #33 have been covered here. @nemesisdesign  Please review! :-)
=> Updated Contributing guidelines

index.rst, user/configure-device.rst
=> [user] Added openwisp-config installation guide

.travis.yml
Reverts openwisp/openwisp2-docs#50
=> Revert "Add Travis Support"

general/code-of-conduct.rst, index.rst
This PR is in reference to the issue #24 
I have added the link to the **code-of-conduct** in `toctree`.
Kindly review the changes 😃
=> Added code-of-conduct

general/glossary.rst, general/help-us.rst, user/configure-device.rst, user/quickstart.rst
I did what the title says! Updated all the links and all that. I forgot to add a little something in my last PR. Sowwy.
=> Replaced 'lede' with 'openwrt'.

user/configure-device.rst
So I added some lines so that people, either students or in general do not face the same issues that I did and save time! Also, please do not remove the GCI task as I have not claimed it yet.
Closes #62
=> [user/configure-device.rst] Made it more beginner-friendly! #62

.travis.yml, README.rst, check_line_length.py, developer/contributing.rst, developer/google-code-in.rst, developer/google-summer-of-code.rst, general/code-of-conduct.rst, general/glossary.rst, general/help-us.rst, general/technologies.rst, general/values.rst, runsphinx-build, user/configure-device.rst, user/quickstart.rst
=> [qa] Added travis build which checks the docs

.travis.yml, requirements.txt
=> [qa] Added commit message style check #76 

check_line_length.py
Check code samples. If it is code samples set line height to 114.
Fixes #70 
Fixes #74
=> [check] Allow skipping line check for code samples and return all errors #70 #74

user/configure-device.rst
Added The \ To Override The Limit Of Character's
=> Added \ To Skip The Character Limit

developer/google-code-in.rst
Added "Suspension of mentors" section according to the discussion on the openwisp-mentors mailing list.
=> [gci] Added "Suspension of mentors" section

developer/contributing.rst
…tering issues in setup
Changed commits from "a different branch" to "your fork" as better represents GitHub and the process needed to be taken. Also tells them about Travis/coveralls and to be patient when waiting for a review.
When an error is encountered during installation, they should ask via communication channels, create an issue for it then are encouraged to try and fix it themselves.
=> [enhancement] Changed information about committing changes and encountering errors

.travis.yml, check_line_length.py, requirements.txt, setup.cfg
Replace old qa checks with `openwisp-utils-qa-checks` (related to openwisp/openwisp-utils#63 for this repo)
=> [qa] Replace with openwisp-utils-qa-checks

general/help-us.rst
* Fix numbering
* Capital letter
Fixes #102
=> [general] Minor improvements #102

user/configure-device.rst
I have updated the guide to make it easier to understand as some who had no previous experience with OpenWISP
=> [user] Update Configure device guide

general/press.rst
@nemesisdesign, wasn't sure of the order at which the link should be added (so added in the end for now).
Also, if you have any better title to suggest please feel free to do so :)
=> [press] Added link to OpenWISP Monitoring GSoC '20 blog

general/press.rst
Adds a link to the blog post regarding my work :)
=> Added blog link for GSoC 2017 Raspbian Backend

.travis.yml, conf.py, developer/hacking-openwisp-python-django.rst, general/press.rst, run-qa-checks
Fixes #111
Although I try to solve all errors, one error still exists in `_templates/layout.html`
=> [qa] Added qa-checks #111

developer/contributing.rst
Fixes: #98 [docs] Make clear to have 1 PR for 1 feature
=> [doc] updated commit guidelines #98

user/configure-push-updates.rst
Related to https://github.com/openwisp/openwisp-controller/pull/349
=> [docs] Updated docs for default access credentials

.github/workflows/ci.yml, general/technologies.rst
=> [docs] Deploy pages built on master #142

developer/contributing.rst
=> [docs] Add link to dev chat #145

_static/style.css
- At `level-4` of current docs, @nemesisdesign  reported  this issue (See below)
=> [docs] Fixed CSS style glitch

.github/workflows/ci.yml
=> [CI] Do not run setup google cloud on pull request #151

user/configuration-variables.rst, user/configure-push-updates.rst
Related to https://github.com/openwisp/openwisp-controller/pull/634
=> [docs] Updated urls to point to docs branch

.github/workflows/ci.yml
Updated OS and python version.
=> [ci] Updated OS and python version

tutorials/hotspot.rst
- Simplified
- Improved English
- Highlighted keywords
=> [chores] Improved hotspot page text

user/configure-push-updates.rst
Related to https://github.com/openwisp/openwisp-controller/pull/782
=> [docs] Recommended use of ED25519 key

developer/gsoc-ideas-2024.rst
=> [gsoc24] Added project idea for netjsongraph.js improvements #185

developer/google-summer-of-code.rst
Added "Application Template" section to GSoC page.
=> [gsoc] Added "Application Template" section

user/usage-metric-collection.rst
Updated "Collection of Usage Metrics" page with changes made in https://github.com/openwisp/openwisp-utils/pull/375.
=> [docs] Updated "Collection of Usage Metrics" page

tutorials/demo.rst, tutorials/hotspot.rst
- Hotspot Tutorial: mention OpenVPN package is required
- Warn about installing coova-chilli from packages
- Fixed reference to alternative firmware instructions
=> [docs] Improvements to hotspot tutorial

_static/custom.css, _templates/downloads.html, _templates/layout.html, _templates/version_switcher.html, conf.py, version_switcher/event_callbacks.py
- Fixed repeated versions in version map on consecutive builds.
- Fixed double logo on narrow screen.
=> [change] Updated version switcher and offline docs URLs

config.yml
=> [docs] Added v24.11

build.py
A regression was added in #221 which skipped uploading local respositories.
Related to #221
=> [fix] Fixed build script to update local respository #221
